---
title: "Lexis Diagram - Project 1 Demography UnB"
author: "Erick Nasareth"
date: "2025-04-22"
output: pdf_document
---

# Pacotes necessários

```{r waning=F}
if(!require(pacman)) install.packages("pacman")
pacman::p_load("tidyverse", "readxl", "LexisPlotR", "stringr", "ggthemes")
```

# Carregando tabelas do SIM e do SINASC

```{r}
death <- read.csv("Data/SIM_2000-2023_RS.csv", sep = ";")
birth <- read.csv("Data/sinasc_2000-2023_RS.csv", sep = ";")
```

# Selecionando somente as colunas e linhas que serão utilizadas de cada banco

```{r}
birth <- birth %>%
  select(Ano.do.nascimento, Total)

death <- death %>%
  select(Ano.do.Obito, Total)

death <- death[1:24, ]
```


# Criando os grupos delimitando os limites


```{r}

intervalos <- rep(seq(from = as.Date("2000-01-01"), to = as.Date("2024-01-01"), by = "5 year"), each = 5)
intervalos <- intervalos[1:(length(intervalos) - 1)]

birth[,"Intervalos"] <- intervalos
death[,"Intervalos"] <- intervalos


```


```{r}
Nascidos <- birth %>%
  select(Total, Intervalos) %>%
  group_by(Intervalos) %>%
  summarise(Nascidos = sum(Total))

Obitos <- death %>%
  select(Total, Intervalos) %>%
  group_by(Intervalos) %>%
  summarise(Obitos = sum(Total))

```



# Criando Poligonos

## Delimitando os limites da coordenada x

```{r}

coordenadas <- rep(seq(from = as.Date("2000-01-01"), to = as.Date("2024-01-01"), by = "5 year"), each = 4)
coordenadas <- coordenadas[3:length(coordenadas)]
coordenadas <- c(coordenadas, c(rep(as.Date("2024-01-01"), each = 2)))

grupo = rep(seq(from = as.Date("2000-01-01"), to = as.Date("2024-01-01"), by = "5 year"), each = 4)
coordx = coordenadas
coordy = rep(c(0, 5, 5, 0), length(unique(grupo)))


```



```{r}
polygons <- data.frame(group = grupo,
                       x= coordx,
                       y= coordy
                             )


  
```


```{r}

lexis_grid(year_start = 2000, year_end = 2025, age_start = 0, age_end = 10, delta = 5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_polygon(aes(      # Polígonos para 1 a 4 anos     
    x     = polygons$x,
    y     = polygons$y,
    group = polygons$group,
    fill  = polygons$group
  ),
  alpha= 0.3) +
  annotate(
    "text",
    x     = seq(from = as.Date("2003-01-01"), to = as.Date("2025-01-01"), by = "5 year"),
    y     = 3,
    label = Obitos$Obitos, # Respostas da questão
    size  = 5,
    color = "red"
  )   +
  annotate(              # Anotações nos gráficos
    "text",
    x     = seq(from = as.Date("2002-06-01"), to = as.Date("2025-01-01"), by = "5 year"),
    y     = 0.5,
    label = Nascidos$Nascidos,     # Respostas da questão
    size  = 5
  ) 



```











